### ISSUE TITLE
LibreLinkUp crashes when last_known is null

### ISSUE THREAD

**Issue by ACWalker** [nightscout/nightscout-connect#27]
I have the following error when using the nightscout-connect plugin `0.0.12` on nightscout version `15.0.1`:

```
 /opt/app/node_modules/nightscout-connect/lib/sources/librelinkup.js:124
       var last_updated = last_known.entries;
                                     ^

 TypeError: Cannot read properties of null (reading 'entries')
     at Object.transformGlucose [as transformer] (/opt/app/node_modules/nightscout-connect/lib/sources/librelinkup.js:124:37)
     at transformService (/opt/app/node_modules/nightscout-connect/lib/machines/fetch.js:14:37)
     at Interpreter._exec (/opt/app/node_modules/xstate/lib/interpreter.js:269:63)
     at Interpreter.exec (/opt/app/node_modules/xstate/lib/interpreter.js:1026:10)
     at Interpreter.execute (/opt/app/node_modules/xstate/lib/interpreter.js:387:14)
     at Interpreter.update (/opt/app/node_modules/xstate/lib/interpreter.js:415:12)
     at /opt/app/node_modules/xstate/lib/interpreter.js:110:15
     at Scheduler.process (/opt/app/node_modules/xstate/lib/scheduler.js:69:7)
     at Scheduler.schedule (/opt/app/node_modules/xstate/lib/scheduler.js:48:10)
     at Interpreter.send (/opt/app/node_modules/xstate/lib/interpreter.js:104:23)
```

It seems the variable `last_known` is no longer used so the line `lib/sources/librelinkup.js:124` can probably be removed.

 I tried contributing myself but I don't have permissions to open a PR :(.

**Comment by billyjbryant** [comment]
I submitted PR #34 that fixes this issue. I tested this by installing `nightscout-connect` from my git repo in `cgm-remote-monitor` then building a container locally. 

When deployed in place of my existing `Nightscout` stack, this fixes the issue with Libre Link up data not populating and the server crashing.

**Comment by AndyLow91** [comment]
Closing as resolved by merged PR #34, with thanks to @billyjbryant. The [current LibreLinkUp implementation](https://github.com/nightscout/nightscout-connect/blob/fe51c6df41e36aa071ff5ec7b24d2e1ee9a77fa9/lib/sources/librelinkup.js) guards a null/missing `last_known` in both fetching and transformation.

During this review, a credential-free check explicitly exercised both paths with a null bookmark and passed. The existing LibreLinkUp/Dexcom regression tests also passed. This resolves the reported null-`entries` crash; separate authentication or API-compatibility problems are not being marked fixed by this closure.
