### ISSUE TITLE
Steps to get this working?

### ISSUE THREAD

**Issue by billreed85** [nightscout/nightscout-connect#3]
I am probably missing something very obvious, but I did the following on my Heroku Nightscout install:

1. Add 'connect' to the ENABLE config var list.
2. Added new config vars for: CONNECT_SOURCE, CONNECT_LINK_UP_USERNAME, CONNECT_LINK_UP_PASSWORD, CONNECT_LINK_UP_REGION, CONNECT_LINK_UP_PATIENT_ID

There is no data coming into the Nightscout site from my Libre 3. Any thoughts on the best way to move forward?

**Comment by bewest** [comment]
Howdy @billreed85, thanks very much for your interest!  To get this running in Nightscout, you'll need to use a branch: `wip/bewest/nightscout-connect`.
* pull request - https://github.com/nightscout/cgm-remote-monitor/pull/7983
Link to branch: https://github.com/nightscout/cgm-remote-monitor/tree/wip/bewest/nightscout-connect

**Comment by bewest** [comment]
It's now possible to use Nightscout's `dev` branch.

**Comment by Chapagain43** [comment]
same here.... 
Pulling this in Azure "nightscout/cgm-remote-monitor-development:latest"
With the following configurations but nothing is getting populated in the website
  {
    "name": "API_SECRET",
    "value": "xxxx",
    "slotSetting": false
  },
  {
    "name": "CONNECT_LINK_UP_CONNECTION",
    "value": "xxxx",
    "slotSetting": false
  },
  {
    "name": "CONNECT_LINK_UP_PASSWORD",
    "value": "xxxx",
    "slotSetting": false
  },
  {
    "name": "CONNECT_LINK_UP_REGION",
    "value": "US",
    "slotSetting": false
  },
  {
    "name": "CONNECT_LINK_UP_SERVER",
    "value": "api-US.libreview.io",
    "slotSetting": false
  },
  {
    "name": "CONNECT_LINK_UP_TIME_INTERVAL",
    "value": "1",
    "slotSetting": false
  },
  {
    "name": "CONNECT_LINK_UP_USERNAME",
    "value": "xxxx",
    "slotSetting": false
  },
  {
    "name": "CONNECT_LOG_LEVEL",
    "value": "info",
    "slotSetting": false
  },
  {
    "name": "CONNECT_SOURCE",
    "value": "linkup",
    "slotSetting": false
  },
  {
    "name": "DOCKER_REGISTRY_SERVER_URL",
    "value": "https://index.docker.io/v1",
    "slotSetting": false
  },
  {
    "name": "ENABLE",
    "value": "connect",
    "slotSetting": false
  },
  {
    "name": "MONGODB_URI",
    "value": "xxxx",
    "slotSetting": false
  },
  {
    "name": "WEBSITES_ENABLE_APP_SERVICE_STORAGE",
    "value": "false",
    "slotSetting": false
  }
]

**Comment by bewest** [comment]
@Chapagain43, I think you have the wrong image/tag name.  Try this one instead:
https://hub.docker.com/r/nightscout/cgm-remote-monitor/tags

`nightscout/cgm-remote-monitor:latest_dev` should resolve to the latest dev image published recently by the build bot.

**Comment by Chapagain43** [comment]
Awesome, thank you.
site is working with latest dev version with the above configurations to pull from librelink
will leave it alone but for last 5 minutes nothing is being entered.

**Comment by bewest** [comment]
Also, I noticed you are interested in using libre; just this morning I pushed new code required for their recent compatibility updates.  I just updated the dev branch to match, and it should be publishing an updated docker image shortly.  Once a new image is listed, it's worth retrying.

**Comment by bewest** [comment]
You can convince yourself that the plugin is available by leaving out your password or username.  If the plugin is configure to be used, but the credentials are empty, it should generate a boot error page that clearly explains the issue.

**Comment by Chapagain43** [comment]
Boom!
Left password out and as expected it threw an error. 

LibreLinkUp Password is required. CONNECT_LINK_UP_PASSWORD must be the password for the LibreLinkUp User in order to login.
{"stack":"Error: CONNECT_LINK_UP_PASSWORD
at Function.validate_inputs [as validate] (/opt/app/node_modules/nightscout-connect/lib/sources/librelinkup.js:219:156)
at manage (/opt/app/node_modules/nightscout-connect/index.js:49:26)
at setupConnect (/opt/app/lib/server/bootevent.js:323:58)
at Object. (/opt/app/node_modules/bootevent/index.js:12:7)
at EventEmitter.saw.nest (/opt/app/node_modules/chainsaw/index.js:86:12)
at Object.acquire (/opt/app/node_modules/bootevent/index.js:10:9)
at saw.next (/opt/app/node_modules/chainsaw/index.js:62:18)
at setupListeners (/opt/app/lib/server/bootevent.js:318:5)
at Object. (/opt/app/node_modules/bootevent/index.js:12:7)
at EventEmitter.saw.nest (/opt/app/node_modules/chainsaw/index.js:86:12)","message":"CONNECT_LINK_UP_PASSWORD"}

**Comment by Chapagain43** [comment]
@bewest,
Really appreciate you walking me thru this. 
I will repull the dev docker in the AM tomorrow to see if it starts to write.
Just to clarify: in the LibreLinkUp it required the nightscout website and api token, assuming from the readme file here no need to include these?

**Comment by bewest** [comment]
Maybe get in touch with me via bewest@gmail.com or on FB.  It would help to be able to test out with credentials that have data.  I don't use Libre, so I was only able to directly test basic login.

**Comment by jonisaksson** [comment]
I have the same problem. It doesnt seem to pull any data through from LibreLinkUp. Was there a solution found for this issue?

**Comment by jonisaksson** [comment]
Thank you Ben,
Unfortunately can’t I seem to get any data to flow through to nightscout
I am following myself, so I am running the Librelinkup app on my iphone and I can see the data in there, so I know the data is getting populated in LibreLinkUp


I am running Nightscout 15.0 (latest dev)

CONNECT_SOURCE                                         = LINKUP
CONNECT_LINK_UP_USERNAME               = xxxx
CONNECT_LINK_UP_PASSWORD              = yyyy
CONNECT_LINK_UP_REGION                      = EU

I have tried changing the region to EU2 to see if that helps (as I am in the UK) but no data is coming through on either region settings.

I deleted the CONNECT_LINK_UP_PASSWORD, and I got an error saying “LibreLinkUp Password is required. “  so the user credentials for librelinkup seem to be correct
Any idea what to test to get the root of this problem

**Comment by bewest** [comment]
There are two passwords, one for LibreLinkup and one for LibreView.  It's possible for them to not match, worth triple checking.

**Comment by jonisaksson** [comment]
Thanks Ben, I did reset both password to be the same password, just to be on the safe side.
During my troubleshooting, I did notice that if you enter the wrong password in the Nightscout, it doesn’t throw an error message, but it will lock the LibreView account ‘due to too many login attempts’.
That made me hopeful, thinking that I had found why I wasn’t getting any data through but even after using 2FA to ‘reopen’ the libreview account, there is still no data flowing through.

It did make me think though, there would be good if there was some code that validated that a connection has been made. At the moment you only get an error message if you have no password, so you no idea what is actually happening as you could be entering the wrong password or the Librelink account could be locked, or something else could be wrong.

Anyway, I am still stuck with not getting any data through… any ideas on what I should look for? There is nothing in the logs, the LibreView password is definitely the right one now.

**Comment by bewest** [comment]
Ok, if you could email me at `bewest` at `medicaldatanetworks.com` or `gmail.com` I will take a look in my development environment.  Otherwise I don't have any access to testing or development.  It would help if you could set a temporary password and send it to my email.  Make sure to mention `nightscout-connect` and libre in the subject.
Out of curiosity, are you able to get it to work with https://github.com/timoschlueter/nightscout-librelink-up?

**Comment by jonisaksson** [comment]
Thank you Ben.

I will send you an email with my login details to Libreview
I have to be honest, I haven’t tried Librelink up

**Comment by bewest** [comment]
@jonisaksson thanks for your help!  I found several issues that needed to be fixed in order for this to work.

How often does LibreLinkUp update with new data for you?
Updated in latest feature branch: https://github.com/nightscout/nightscout-connect/pull/19

**Comment by jonisaksson** [comment]
Thank you Ben!

I haven’t been using the Libre as a CGM (rather used xDrip4iOS), so I think it only updates when I scan the sensor. The plan is to move to use Libreview with the CGM feature and have nightscout feed xDrip4iOS (in follower mode)

**Comment by AndyLow91** [comment]
Closing this historical setup/support thread rather than marking all LibreLinkUp connection failures as fixed. The original discussion concerned pre-release Nightscout integration, image/branch selection and follower configuration; the maintainer subsequently addressed the compatibility problems through merged PR #19.

For current configuration, use the [LibreLinkUp section of the README](https://github.com/nightscout/nightscout-connect/blob/fe51c6df41e36aa071ff5ec7b24d2e1ee9a77fa9/README.md#libre-link-up), including `CONNECT_SOURCE=linkup`, the follower account credentials, the correct account region and an optional patient ID when needed. An absent-password boot error only confirms that the plugin is enabled; it does not validate the account or prove a successful connection.

Current problems should be investigated in focused reports: #57 tracks the UK-region question and PR #53 proposes newer authentication-header compatibility. Neither is being marked resolved here. If another failure persists, please provide the Nightscout/connector versions, selected region, failure stage and HTTP status, without credentials, cookies or patient records. Thank you to everyone who helped work through the initial setup.
