### ISSUE TITLE
Can't get Glooko connect to work

### ISSUE THREAD

**Issue by fclingen** [nightscout/nightscout-connect#44]
I'm a newbie, I'm undoubtedly doing something wrong.

I've had cgm-remote-monitor running for years on Heroku, taking data from the REST API in Xdrip+. I'm trying to change it to take connect data from Glooko because I have a Pod 5 doing the looping for me and the Pod 5 controller connects to Glooko out of the box.

The master branch of cgm-remote-monitor appears to have nightscout-connect in it's plugins? I can run nightscout-connect from the master branch (I just updated my repo, but it has been running for years otherwise). I've set my config variables as given in the README here. 

When I run:

```nightscout-connect forever --source "glooko"`

I get:

```
STARTING {
  _: [ 'forever' ],
  source: 'glooko',
  hint: 'glooko',
  glookoServer: 'api.glooko.com',
  glookoEmail: 'myemail@email.fake',
  glookoTimezoneOffset: -5,
  glookoPassword: 'myfakepassword',
  '$0': 'nightscout-connect'
}
CONFIGURED OUTPUT { name: 'nightscout', url: undefined, apiSecret: undefined }
CONFIGURED INPUT { kind: 'glooko', url: undefined, apiSecret: undefined }
SELECTING OUTPUT { name: 'nightscout', url: undefined, apiSecret: undefined } nightscout [Function: nightscoutRestAPI]
SETTING UP nightscoutRestAPI { name: 'nightscout', url: undefined, apiSecret: undefined }

... a bunch of raw javascript-looking code ...


TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Url.parse (node:url:168:3)
    at Object.urlParse [as parse] (node:url:155:13)
    at nightscoutRestAPI (/app/node_modules/nightscout-connect/lib/outputs/nightscout.js:15:22)
    at sidecarLoop (/app/node_modules/nightscout-connect/commands/forever.js:14:33)
    at Object.main [as handler] (/app/node_modules/nightscout-connect/commands/forever.js:45:16)
    at /app/node_modules/nightscout-connect/node_modules/yargs/build/index.cjs:1:8993
    at j (/app/node_modules/nightscout-connect/node_modules/yargs/build/index.cjs:1:4956)
    at _.handleValidationAndGetResult (/app/node_modules/nightscout-connect/node_modules/yargs/build/index.cjs:1:8962) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

If I try to fork out of nightscout/nightscout-connect and deploy, my app fails to run, and I don't understand the errors it is giving me in the logs. It doesn't look like anything.  Since the error looks like some URL is missing I've tried to manually set CONNECT_GLOOKO_SERVER to its default but that doesn't appear to make any difference.

**Comment by 4gra** [comment]
I think it's looking for you to set the `CONNECT_NIGHTSCOUT_ENDPOINT` variable in your environment file.   See in the logs where it says `CONFIGURED OUTPUT { name: 'nightscout', url: undefined, apiSecret: undefined }`, this should be your Nightscout server and port as per the README . You'll need to find and set the API secret, too of course.

**Comment by AndyLow91** [comment]
The trace here identifies a missing Nightscout output configuration, not an incorrect Glooko server: the standalone `nightscout-connect forever` command selected REST output with both `url` and `apiSecret` undefined. Configure `CONNECT_NIGHTSCOUT_ENDPOINT` with the destination Nightscout URL and `CONNECT_API_SECRET` with its API secret when using that standalone mode. Do not post the secret here.

When using Nightscout's embedded plugin instead, enable `connect` in Nightscout's ENABLE setting and supply the Glooko source settings; a separate `forever` process is not needed. The merged branch now reports explicit missing-endpoint/missing-secret errors, with tests, instead of the opaque `url.parse(undefined)` failure. Both REST and embedded writes were tested. Closing this diagnosed configuration/error-reporting issue as addressed.

PR #71 is merged into `dev` at `fe51c6d`. [Post-merge CI passed on Node 22 and 24](https://github.com/nightscout/nightscout-connect/actions/runs/35659349723), with 122 regression tests. [Live validation and its limits](https://github.com/nightscout/nightscout-connect/blob/fe51c6df41e36aa071ff5ec7b24d2e1ee9a77fa9/docs/glooko-live-test-plan.md#verification-status) are recorded in the repository. This is available in the connector's `dev` branch; merging here does not automatically update the connector bundled in an existing Nightscout deployment.
